### ISSUE TITLE
Create challenge review rubric for RPS

### ISSUE THREAD

**Issue by silvabox** [makersacademy/rps-challenge#178]

**Comment by tansaku** [comment]
in progress here: https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md

**Comment by tansaku** [comment]
we don't like global variables; http://c2.com/cgi/wiki?GlobalVariablesAreBad

**Comment by tansaku** [comment]
* [ ] sort README screenshot thing
* [ ] folder layout
* [ ] code examples for application section
  * [ ] presentation strings in business logic layer
  * [ ] if else conditionals
  * [ ] encapsulation
  * [ ] POSTing to /result
  * [ ] calling business logic from the view
  * [ ] fat controllers
* [ ] global vars section
