### ISSUE TITLE
Under ‘Use of Global Variables’ in review.md

### ISSUE THREAD

**Issue by Andrew47** [makersacademy/rps-challenge#248]
Tried to follow the method suggested, but found that my rspec tests failed. Then, I found that adding `Player.players` to the method `add_player` led to the tests passing. Perhaps this is a requirement in order to have an empty hash to which players can be added. Is this a problem with the code review rubric?

**Comment by neoeno** [comment]
Has been fixed since, I think. Sorry for the old notification spam Andrew! Hope all's well
