### ISSUE TITLE
Hound spam on pull requests

### ISSUE THREAD

**Issue by domvernon** [makersacademy/rps-challenge#868]
On each of the pull requests, there seems to be a lot of the same messages:

```
Some files could not be reviewed due to errors:

.rubocop.yml: Style/IndentationConsistency has the wrong namespace - should b...
```
It would appear that Rubocop has introduced changes to how it's 'cops' are categorised and hence the messages. Hound is therefore using a different version of Rubocop to the one listed in the Gemfile.

To fix this I have taken the following steps:
1. `bundle update rubocop`
2. `bundle install` (to make sure the dependencies are updated)
3. `gem install mry` 
4.  `mry .rubocop.yml` (these steps update the config file with the new options that were changed)

It was at this point I realised Hound isn't even using the latest version of Rubocop so I have fixed the Rubocop version at 0.51.0 and repeated the process. I have no warnings locally and no error messages on my pull request.

Does this sound correct? I don't seem to have any feedback from Hound at all.

**Comment by mdsomerfield** [comment]
Where did you find the version of Rubocop that Hound is using? I can't see any reference to Rubocop at all in the current Hound gemfile: https://github.com/houndci/hound/blob/master/Gemfile

**Comment by domvernon** [comment]
It's in their linters repository:
https://github.com/houndci/linters/blob/e7f99de6fc4fdcbb4bd21f2d3db2ef87c4b2bd5b/Gemfile.lock#L78

**Comment by mdsomerfield** [comment]
So that's telling us any version > 0.47.0. So it feels like they'll be on the latest version when they next release (assuming their build process is sensible). On that basis, I'm inclined to leave the challenge gem file as is since this will likely resolve the next time the challenge comes around.

**Comment by domvernon** [comment]
That sounds sensible, I'll close the issue.
